plugins(squelch_uploader): fix plugin_api.h include path
In-tree plugin builds don't get the repo root on their include path
(only `lib/` is added globally for json.hpp). Use the relative path
that the bundled openmhz / rdioscanner / broadcastify plugins use:

    #include "../../trunk-recorder/plugin_manager/plugin_api.h"

Fixes:

    /src/plugins/squelch_uploader/squelch_uploader.cc:20:10:
    fatal error: trunk-recorder/plugin_manager/plugin_api.h:
    No such file or directory